[buildPlans.iosevka-zt]
family = "Iosevka ZT"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.iosevka-zt.variants]
  inherits = "ss05"

    [buildPlans.iosevka-zt.variants.design]
    capital-q = "crossing"
    capital-u = "toothless-corner-serifless"
    a = "single-storey-tailed"
    i = "serifed-flat-tailed"
    lower-delta = "flat-top"
    lower-lambda = "tailed-turn"
    lower-xi = "flat-top"
    zero = "oval-slashed"
    three = "flat-top-serifless"
    ampersand = "upper-open"
    percent = "rings-continuous-slash-also-connected"
    bar = "force-upright"

    [buildPlans.iosevka-zt.variants.italic]
    capital-q = "curly-tailed"
    f = "tailed"
    k = "cursive-bottom-right-serifed"
    u = "tailed-serifless"

  [buildPlans.iosevka-zt.ligations]
  inherits = "dlig"

[buildPlans.iosevka-zt.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-zt.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-zt.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-zt.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-zt.weights.Bold]
shape = 700
menu = 700
css = 700
