# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  iosevka = {
    pname = "iosevka";
    version = "v24.1.3";
    src = fetchFromGitHub {
      owner = "be5invis";
      repo = "Iosevka";
      rev = "v24.1.3";
      fetchSubmodules = false;
      sha256 = "sha256-LM47tiFZ5rDGgRqvGZEoCSpij4ZEoulnsAiM2ZlP7fY=";
    };
  };
}
