on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: actions/checkout@v3
      - name: Run Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v1 
      - name: Build zipfile
        run: |
          nix build -vL
          cp -vL ./result/* ./iosevka.zip
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.TOKEN }}"
          prerelease: false
          files: |
            iosevka.zip
          
