on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: experimental-features = nix-command flakes
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build zipfile
        run: |
          nix build -L
          cp -vL ./result ./iosevka.zip
      - uses: ncipollo/release-action@v1
        name: Release
        with:
          omitBody: true
          omitName: true
          artifacts: "iosevka.zip"
