on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: |
          nix build -L
          cp -vL result/*.tlz ./
      - name: Release
        uses: ncipollo/release-action@main
        with:
          token: "${{ secrets.TOKEN }}"
          artifacts: "*.tlz"
          omitBody: true
          allowUpdates: true
          omitName: true
          replacesArtifacts: true
