on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build zipfile
        run: |
          nix build -L
          cp -vL result/*.tar.xz ./
      - name: Release
        uses: ncipollo/release-action@latest
        with:
          token: "${{ secrets.TOKEN }}"
          artifacts: "*.tar.xz"
          omitBody: true
          allowUpdates: true
          omitName: true
          replacesArtifacts: true
